/**
 * Created by Phil on 2/8/2016.
 */
/**
 * @ngdoc object
 * @name wedSite.models.teamModel
 * @description
 * class model factory
 * @requires ex.breeze
 *
 */

angular.module('wedSite.models')
    .factory('TeamModel',[
        'breeze',
        'ENTITY_TYPES',
        function (breeze, ENTITY_TYPES) {
            var DT = breeze.DataType;
            return {
                meta: {
                    namespace: "wedSite",
                    shortName: ENTITY_TYPES.TEAM_ENTITY,
                    defaultResourceName: ENTITY_TYPES.TEAM_ENTITY,
                    autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity,
                    dataProperties: {
                        Team: {dataType: DT.String, isPartOfKey: true},
                        arrest_count: {dataType: DT.Int32}
                    },
                    navigationProperties:{
                    }
                },
                init : function (metadataStore) {
                    metadataStore.addEntityType(this.meta);
                }
            };
        }
    ])
;